name: CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'lacam/**'
      - 'tests/**'
      - 'main.cpp'
      - '.github/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: submodule setup for google test
        uses: actions/checkout@v4
        with:
          repository: google/googletest
          path: third_party/googletest
      - name: submodule setup for argparse
        uses: actions/checkout@v4
        with:
          repository: p-ranav/argparse
          path: third_party/argparse
      - name: build
        run: ./build.sh
      - name: test
        run: ./build/test_all
